# Generated by Django 3.2 on 2021-06-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cost',
        ),
    ]
